### ISSUE TITLE
How to Set APPIUM_HOST to container hostname

### ISSUE THREAD

**Issue by rlupo09** [butomo1989/docker-android#65] opened 2018-02-13 01:19 UTC
I'm attempting to set the environment variable APPIUM_HOST to the hostname of the container.

I'm not sure if you're familiar with the docker image selenium/node-chrome, but there you're able to override the host and set it to the container hostname by doing entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

Selenium Chrome node .yml example

chrome:
  image: selenium/node-chrome:3.7.1
  ports:
    - "5556:5556"
  depends_on:
    - hub
  environment:
    - HUB_PORT_4444_TCP_ADDR=hub
    - HUB_PORT_4444_TCP_PORT=4444
  entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

Would you happen to know how to set the APPIUM_HOST to the hostname of the container? 

  SamsungGalaxyS6:
    image: butomo1989/docker-android-x86-7.1.1
    ports:
      - 6080:6080
    environment:
      - DEVICE=Samsung Galaxy S6
      - APPIUM=True
      - CONNECT_TO_GRID=True
      - SELENIUM_HOST=hub
      - SELENIUM_PORT=4450
  entrypoint: bash -c {How to set appium_host to container hostname}

Use Case:
I'm running on a docker swarm and my reason to set the APPIUM_HOST to the container hostname is that a container can have multiple interfaces when we start appium it tries to make a guess based on the interfaces available. It then sends this address to the hub to contact it back. In case of multiple interfaces the address can be determined wrongly and the hub is not able to communicate back with the node.

To fix this issue we need to ourself determine the hostname of the container.

**Comment by butomo1989** [comment] 2018-02-13 16:33
Hi @rlupo09 , 

could you try to pass APPIUM_HOST in environment variable to overwrite the default value?

**Comment by butomo1989** [comment] 2018-02-13 16:34
I will close this ticket because I feel that it is not a bug. please feel free to reopen it if there is a bug. and please join our group chat https://gitter.im/butomo1989/docker-android for further questions.

**Closed by butomo1989** 2018-02-13 16:34 UTC

**Comment by rlupo09** [comment] 2018-02-13 17:09
Hi @butomo1989,

It's not a bug, but a help wanted. Yes I can override the default value with the APPIUM_HOST, but how would one get the hostname of the container to override the default value with.

**Comment by butomo1989** [comment] 2018-02-14 09:28
Hi @rlupo09 , 

If you can try to run command "hostname -i” inside container or if you find the ip from host machine, you can pass through command “export”, e.g. https://github.com/zalando-incubator/docker-locust/blob/master/local.sh#L161-L164. I hope it helps :)

**Comment by rlupo09** [comment] 2018-02-15 00:15
Thank you butomo1989. 

```  command: bash -c 'APPIUM_HOST=$$(hostname -i) /usr/bin/supervisord --configuration supervisord.conf' ```
