### ISSUE TITLE
most of the containers are unusable on Mac 10.12.5

### ISSUE THREAD

**Issue by vikramvi** [butomo1989/docker-android#36] opened 2017-08-14 14:00 UTC
Mac 10.12.5 + docker Version:      17.06.0-ce

Below containers are unusable as status is always unhealthy and vnc shows emulator in starting phase always even after 5 minues

- 5.1.1
- 6.0 
- 7.0
- 7.1

Used below command as per README

`docker run --privileged -d -p 6080:6080 -p 5554:5554 -p 5555:5555 -e DEVICE="Samsung Galaxy S6" --name android-container_6 butomo1989/docker-android-arm-7.1.1`

changed last value of OS to above list of failed OS.

Am I doing something wrong here ?

**Comment by butomo1989** [comment] 2017-08-18 11:18
Hi @vikramvi , 

It is because you are using arm images. you need to use ubuntu OS with x86 image to get best performance. arm image take normally around 10 min (it might take longer -> it depends on your RAM and other reasons). I will close this issue because it is not a bug. in the future I might only support x86 image and you can use VMWare player to simulate ubuntu OS.

**Closed by butomo1989** 2017-08-18 11:18 UTC

**Comment by vikramvi** [comment] 2017-08-22 12:22
@butomo1989 can you please add this important point in README as first time users may wonder what's going wrong.

Can you explain in detail how do you use Ubuntu OS with Mac ?

**Comment by butomo1989** [comment] 2017-08-22 12:37
Hi @vikramvi ,

I just created issue #37. I will try to do it if I have time but it might take a while. :( I really hope somebody can jump to work on that issue.
