### ISSUE TITLE
win7 docker-appium (exit status 1; not expected)

### ISSUE THREAD

**Issue by Louis-me** [butomo1989/docker-android#25] opened 2017-07-18 09:51 UTC
win7:

```
$ docker-compose up
....
amsung_galaxy_web_7.1.1_1  | 2017-07-18 02:27:20,581 INFO exited: docker-appium (exit status 1; not expected)
amsung_galaxy_web_5.1.1_1  | 2017-07-18 02:27:25,056 INFO exited: docker-appium (exit status 1; not expected)
```

chrome borowser:
![image](https://user-images.githubusercontent.com/3804513/28310905-84914420-6be0-11e7-91aa-5ecb7840a233.png)

- yesterday, used your dockerfile and docker-compose is ok.today use  docker-compose I get back this  error message

pls help me! thank you

**Comment by butomo1989** [comment] 2017-07-18 09:53
Hi @Louis-me ,

Thank you for opening this issue. I assume it is because you are using x86 image. https://github.com/butomo1989/docker-android/blob/master/docker-compose.yml#L33
you need to change it to arm image, because you are using windows OS, you can find that image name in readme.

**Comment by butomo1989** [comment] 2017-07-18 09:54
@Louis-me you can also join our chat room: https://gitter.im/butomo1989/docker-android in case you have more questions.

**Comment by butomo1989** [comment] 2017-07-19 10:09
I close this issue because it is not a bug

**Closed by butomo1989** 2017-07-19 10:09 UTC
