### ISSUE TITLE
Error building x86 image on master

### ISSUE THREAD

**Issue by Kignuf** [butomo1989/docker-android#77] opened 2018-05-17 16:10 UTC
Hello Budi, I hope you are well.
I am running into an issue when building the docker x86 image, from current master. I'm getting an error at step 15
```
docker build -f docker/Emulator_x86 .
Step 15/26 : RUN echo y | sdkmanager "platforms;android-${API_LEVEL}" &&     echo y | sdkmanager "system-images;android-${API_LEVEL};${IMG_TYPE};${SYS_IMG}" &&     echo y | sdkmanager "emulator"
 ---> Running in 5dcc1fb2aa8c
done
Warning: An error occurred while preparing SDK package Google APIs Intel x86 Atom_64 System Image: archive is not a ZIP archive.
The command '/bin/sh -c echo y | sdkmanager "platforms;android-${API_LEVEL}" &&     echo y | sdkmanager "system-images;android-${API_LEVEL};${IMG_TYPE};${SYS_IMG}" &&     echo y | sdkmanager "emulator"' returned a non-zero code: 1
```

Operating System: 
Linux version 3.16.0-5-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08)

Docker Version:  
Docker version 17.05.0-ce, build 89658be

## Expected Behavior
I am able to build the image

## Actual Behavior
```
Warning: An error occurred while preparing SDK package Google APIs Intel x86 Atom_64 System Image: archive is not a ZIP archive.
The command '/bin/sh -c echo y | sdkmanager "platforms;android-${API_LEVEL}" &&     echo y | sdkmanager "system-images;android-${API_LEVEL};${IMG_TYPE};${SYS_IMG}" &&     echo y | sdkmanager "emulator"' returned a non-zero code: 1
```

**Comment by butomo1989** [comment] 2018-05-17 16:29
Hi @Kignuf , 

Thank you for contacting me. You can take a look release.sh to see how I build the image, but the easiest way is to use my docker-image as base and you can extend it from there. 

I'll close this issue because it is not a bug. Feel free to reopen it if needed.

**Closed by butomo1989** 2018-05-17 16:29 UTC

**Comment by Kignuf** [comment] 2018-05-21 13:03
Thanks for the answer. I managed to make a build locally.
I wanted to add some options to the way the emulator is started, so I think I couldn't do that by extending your image.
