### ISSUE TITLE
does this support native app automation as well ?

### ISSUE THREAD

**Issue by vikramvi** [butomo1989/docker-android#29] opened 2017-08-11 12:38 UTC
@butomo1989  please clarify if I can use this for native android app automation as well ?

Or it only used for mobile browser web UI automation ?

**Comment by alanbueno** [comment] 2017-08-11 14:29
Hi @vikramvi, I'm coding automation for native apps and running on these emulated devices.
It works very well.

**Comment by vikramvi** [comment] 2017-08-11 14:47
@alanbueno can you please explain your setup using this container based emualtor ?

My current setup is as follows

- bring up available android emulators
- start appium server
- start selenium hub and register nodes
- run tests in parallel with TestNG

**Comment by butomo1989** [comment] 2017-08-11 15:46
Hi @vikramvi ,

I will close this PR because it is not a bug. maybe we can discuss about it in our group chat: https://gitter.im/butomo1989/docker-android

**Closed by butomo1989** 2017-08-11 15:46 UTC

**Comment by vikramvi** [comment] 2017-08-14 08:21
@alanbueno can you please clarify as per my last comment ?

**Comment by alanbueno** [comment] 2017-08-14 16:33
Hi @vikramvi, sure. I'll answer on our group chat: https://gitter.im/butomo1989/docker-android
